openapi: 3.0.0
info:
  description: The specification for the REST API of Neil.
  version: 0.0.1
  title: the REST API of Neil
paths:
  /chain:
    get:
      description: Returns chain which exists in the Neil node.
      operationId: getChain
      responses:
        200:
          description: Chain which exists in the Neil node.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Block'
              example: >-
                [
                  {
                    "Index": 0,
                    "Timestamp": 1537683239,
                    "Data": "R2VuZXNpcyBCbG9jaw==",
                    "PrevBlockHash": "",
                    "Hash": "00ykmECYY7f8+qVmqlD7tMva1sxYfUx6UymI+s42bDE=",
                    "Transactions": []
                  },
                  {
                    "Index": 1,
                    "Timestamp": 1537683239,
                    "Data": "U2FtcGxlIGJsb2Nr",
                    "PrevBlockHash": "00ykmECYY7f8+qVmqlD7tMva1sxYfUx6UymI+s42bDE=",
                    "Hash": "lnKgwsyKWyL3UQLYQEvggT3W1Qj30cxQLP+fuRqBgTA=",
                    "Transactions": [
                      {
                        "Sender": "Qm9i",
                        "Recipient": "SXZhbg==",
                        "Amount": 1
                      },
                      {
                        "Sender": "Qm9i",
                        "Recipient": "SXZhbg==",
                        "Amount": 2
                      }
                    ]
                  }
                ]
                \
  /transactions/new:
    post:
      description: Post new transaction
      operationId: postTransaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        201:
          description: A transaction is created successfully.
        500:
          description: Internal server error.
components:
  schemas:
    Block:
      type: object
      properties:
        Index:
          type: integer
          format: int64
        Timestamp:
          type: integer
          format: int64
          example: 1537608825
        Data:
          type: string
          example: R2VuZXNpcyBCbG9jaw==
        PrevBlockHash:
          type: string
          example: xKt+P2UbcN1ouK9Mv03K3QNOBP0PJSCVcEr000rk/pc=
        Hash:
          type: string
          example: 8fKKuciRH34TQueQn31JINNPKscdVFN1GNKERA5J3IU=
        Transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Transaction:
      type: object
      properties:
        Sender:
          type: string
          example: Qm9i
        Recipient:
          type: string
          example: SXZhbg==
        Amount:
          type: integer
          format: int64
          example: 3
