openapi: 3.0.0
info:
  description: The specification for the REST API of Neil.
  version: 0.0.1
  title: the REST API of Neil
paths:
  /blocks:
    get:
      description: Returns all blocks which exists in the Neil node.
      operationId: getBlocks
      responses:
        200:
          description: All blocks which exists in the Neil node.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Block'
              example: >-
                [
                  {
                    "Timestamp": 1537674920,
                    "Data": "R2VuZXNpcyBCbG9jaw==",
                    "PrevBlockHash": "",
                    "Hash": "bpN93jZa5YYoINUMa+KA67ATy5FhRMK8hckeOZTgWd4=",
                    "Transactions": []
                  },
                  {
                    "Timestamp": 1537674920,
                    "Data": "U2FtcGxlIGJsb2Nr",
                    "PrevBlockHash": "bpN93jZa5YYoINUMa+KA67ATy5FhRMK8hckeOZTgWd4=",
                    "Hash": "xH+GiFs3mHuonyNnMAHT7YXFsYy9pzT+u2kxcURRxDY=",
                    "Transactions": [
                      {
                        "Sender": "Qm9i",
                        "Recipient": "SXZhbg==",
                        "Amount": 1
                      },
                      {
                        "Sender": "Qm9i",
                        "Recipient": "SXZhbg==",
                        "Amount": 2
                      }
                    ]
                  }
                ]
                \
components:
  schemas:
    Block:
      type: object
      properties:
        Timestamp:
          type: integer
          format: int64
          example: 1537608825
        Data:
          type: string
          example: R2VuZXNpcyBCbG9jaw==
        PrevBlockHash:
          type: string
          example: xKt+P2UbcN1ouK9Mv03K3QNOBP0PJSCVcEr000rk/pc=
        Hash:
          type: string
          example: 8fKKuciRH34TQueQn31JINNPKscdVFN1GNKERA5J3IU=
        Transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Transaction:
      type: object
      properties:
        Sender:
          type: string
          example: Qm9i
        Recipient:
          type: string
          example: SXZhbg==
        Amount:
          type: integer
          format: int64
          example: 3
